web/router.ex
defmodule ExampleCrm.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExampleCrm do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/contacts", ContactsController, only: [:new, :create, :show]
    resources "/activities", ActivitiesController, only: [:create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExampleCrm do
  #   pipe_through :api
  # end
end

lib/example_crm/endpoint.ex
defmodule ExampleCrm.Endpoint do
  use Phoenix.Endpoint, otp_app: :example_crm

  # Serve at "/" the given assets from "priv/static" directory
  plug Plug.Static,
    at: "/", from: :example_crm,
    only: ~w(css images js favicon.ico robots.txt)

  plug Plug.Logger

  # Code reloading will only work if the :code_reloader key of
  # the :phoenix application is set to true in your config file.
  plug Phoenix.CodeReloader

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_example_crm_key",
    signing_salt: "DXs4KGxG",
    encryption_salt: "bQKSw/qo"

  plug :router, ExampleCrm.Router
end

lib/example_crm/repo.ex
defmodule ExampleCrm.Repo do
  use Ecto.Repo, otp_app: :example_crm
end

web/models/activity.ex
defmodule ExampleCrm.Activity do
  use Ecto.Model

  schema "activities" do
    field :time, :string
    field :title, :string
    field :notes, :string
    belongs_to :contact, ExampleCrm.Contact
  end
end

web/models/contact.ex
defmodule ExampleCrm.Contact do
  use Ecto.Model

  schema "contacts" do
    field :firstname, :string
    field :lastname, :string
    has_many :activities, ExampleCrm.Activity
  end

  def changeset(params, :create) do
    %ExampleCrm.Contact{}
      |> cast(params, ~w(firstname lastname))
      |> validate_length(:firstname, min: 1)
      |> validate_length(:lastname, min: 1)
  end
end

web/models/contact_queries.ex
defmodule ExampleCrm.ContactQueries do
  import Ecto.Query

  def all_contacts do
    query = from contact in ExampleCrm.Contact,
              select: contact
    ExampleCrm.Repo.all(query)
  end

end

web/controllers/activities_controller.ex
defmodule ExampleCrm.ActivitiesController do
  use ExampleCrm.Web, :controller

  plug :action

  def create(conn, %{"time" => time, "title" => title, "notes" => notes, "contact_id" => contact_id_str}) do
    {contact_id, ""} = Integer.parse(contact_id_str)
    activity = %ExampleCrm.Activity{time: time, title: title, notes: notes, contact_id: contact_id}
    Repo.insert(activity)
    redirect conn, to: contacts_path(conn, :show, contact_id)
  end
end

web/controllers/contacts_controller.ex
defmodule ExampleCrm.ContactsController do
  use ExampleCrm.Web, :controller

  plug :action

  def new(conn, _params) do
    contact = %ExampleCrm.Contact{}
    render conn, "new.html",contact: contact
  end

  def create(conn, %{"contact" => contact}) do
    changeset = ExampleCrm.Contact.changeset(contact, :create)
    if changeset.valid? do
      Repo.insert(changeset)
      redirect conn, to: "/"
    else
      render conn, "new.html", contact: changeset.changes, errors: changeset.errors
    end
  end

  def show(conn, %{"id"=>id}) do
    contact = ExampleCrm.Repo.get(ExampleCrm.Contact, id)
    activities = ExampleCrm.Repo.all Ecto.Model.assoc(contact, :activities)
    render conn, "show.html", contact: contact, activities: activities
  end
end

web/controllers/page_controller.ex
defmodule ExampleCrm.PageController do
  use ExampleCrm.Web, :controller

  plug :action

  def index(conn, _params) do
    contacts = ExampleCrm.ContactQueries.all_contacts
    render conn, "index.html", contacts: contacts
  end
end

web/views/contacts_view.ex
defmodule ExampleCrm.ContactsView do
  use ExampleCrm.Web, :view
end

web/views/error_view.ex
defmodule ExampleCrm.ErrorView do
  use ExampleCrm.Web, :view

  def render("404.html", _assigns) do
    "Page not found - 404"
  end

  def render("500.html", _assigns) do
    "Server internal error - 500"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule ExampleCrm.LayoutView do
  use ExampleCrm.Web, :view
end

web/views/page_view.ex
defmodule ExampleCrm.PageView do
  use ExampleCrm.Web, :view
end

web/templates/contacts/new.html.eex
<div class="row">
<%= form_tag(contacts_path(@conn, :create), method: :post, class: "form-horizontal") %>
  <div class="form-group">
    <label for="contact[firstname]" class="col-sm-2 control-label">First name</label>
    <div class="col-sm-10">
      <input type="text" name="contact[firstname]" class="form-control"
                                                   id="contact[firstname]" value="<%= @contact.firstname %>" />
    </div>
  </div>
  <div class="form-group">
    <label for="contact[lastname]" class="col-sm-2 control-label">Last name</label>
    <div class="col-sm-10">
      <input type="text" name="contact[lastname]" class="form-control" id="contact[lastname]"
                                                                       value="<%= @contact.lastname %>"/>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>
</div>

web/templates/contacts/show.html.eex
<h1>Details</h1>
<p><%=@contact.firstname%> <%=@contact.lastname%></p>
<h3>Log your history here:</h3>
<%= form_tag(activities_path(@conn, :create),method: :post, class: "form-horizontal") %>
  <input type="hidden" name="contact_id" value="<%=@contact.id%>">
  <div class="form-group">
    <label for="time">When</label>
    <input type="text" class="form-control" name="time" id="time">
  </div>

  <div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control" name="title" id="title">
  </div>

  <div class="form-group">
    <label for="notes">notes</label>
    <input type="text" class="form-control" name="notes" id="notes">
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-default">Submit</button>
  </div>
</form>
<table>
  <thead>
    <th>When</th>
    <th>What</th>
    <th>Notes</th>
  </thead>
  <tbody>
    <%= for activity <- @activities do %>
      <tr>
        <td><%=activity.time%></td>
        <td><%=activity.title%></td>
        <td><%=activity.notes%></td>
      </tr>
    <% end %>
  </tbody>
</table>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>example crm</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <%= @inner %>


    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>

web/templates/page/index.html.eex
<h1>example crm</h1>
<div class="row">
  <div class="col-xs-12">
    <a href="<%= contacts_path(@conn,:new)%>">new contact</a>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <table class="table">
      <thead>
        <th>First name</th>
        <th>Last name</th>
      </thead>
      <tbody>
        <%= for contact <- @contacts do %>
          <tr>
            <td>
              <a href="<%= contacts_path(@conn, :show, contact.id) %>">
                <%= contact.firstname %>
              </a>
            </td>
            <td><%= contact.lastname %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>